server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Documents/java/transport/cloud-config/

eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
