server:
  port: 0

spring:
  application:
    name: registration
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27020
      database: test
      authentication-database: admin
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true